# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Media de un vector usando C++.
#' @param x numeric vector
#' @export
#' @return la media.
meanC <- function(x) {
    .Call('_prueba_meanC', PACKAGE = 'prueba', x)
}

#' Varianza de un vector usando C++.
#' @param x numeric vector
#' @export
#' @return la varianza.
varC <- function(x) {
    .Call('_prueba_varC', PACKAGE = 'prueba', x)
}

